version: '3'
services:
  hello-service:
    image: dan/eureka-client
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.01"  
          memory: 500M 
      restart_policy:  
        condition: on-failure  
    ports:
      - "8763:8763"
    networks:  
      - webnet

networks:  
  webnet: 


